name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: build
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build

    - name: lint / test / coverage
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test:full

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
