name: Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint

      - name: Test / Coverage
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test:coverage

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
